GET http://localhost:3001/user

###

GET http://localhost:3001/user/2

###

POST http://localhost:3001/user
content-type: application/json

{
    "id": "",
    "username": "diego",
    "password": "string",
    "email": "",
    "firstname": "string",
    "lastname": "string",
    "isAdmin": true,
    "created": "Date",
    "updated": "Date"
}

###
POST http://localhost:3001/user/login/1
content-type: application/json

{
    "id": "1",
    "password": "string"
}
###
GET http://localhost:3001/user/login/

